* 定义快捷键
  #+NAME: key-bindings
  | key | function       | comment              |
  |-----+----------------+----------------------|
  | r | org-remember   |                      |
  | l | org-store-link |                      |
  | c | org-capture    |                      |
  | a | org-agenda     |                      |
  | b | org-iswitchb   |                      |
  | <f11> | org-clock-goto | f11:跳转到正在计时的任务 |
  |     |                |                      |
  
  #+BEGIN_SRC emacs-lisp :var keys=key-bindings[2:-1]
    (mapc (lambda (key)
            (let ((k (car key))
                  (f (intern (cadr key))))
              (when (functionp f)
                (global-set-key (kbd k) f))))
          keys)
  #+END_SRC

* 配置agenda
  通过`C-c ['和`C-c ]'可以从`org-agenda-files'中添加/删除当前org文件.
  
  org-agenda-files中的元素还可以是目录,这时目录下的所有匹配`org-agenda-file-regexp'的文件都自动加入agenda
  #+BEGIN_SRC emacs-lisp
    (setq org-agenda-files (list (concat GTD-HOME-PATH "home.org")
                                 (concat GTD-HOME-PATH "office.org")
                                 (concat GTD-HOME-PATH "sms-bank.org")))
    (setq org-agenda-include-diary t)       ;将diary的事项也纳入agenda中显示
  #+END_SRC
* Task and States 
** TODO关键字设置
   #+BEGIN_SRC emacs-lisp
     (setq org-todo-keywords
           (quote ((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d)")
                   (sequence "WAITING(w@/!)" "HOLD(h@/!)" "|" "CANCELLED(c@/!)" "PHONE" "MEETING"))))

     (setq org-todo-keyword-faces
           (quote (("TODO" :foreground "red" :weight bold)
                   ("NEXT" :foreground "blue" :weight bold)
                   ("DONE" :foreground "forest green" :weight bold)
                   ("WAITING" :foreground "orange" :weight bold)
                   ("HOLD" :foreground "magenta" :weight bold)
                   ("CANCELLED" :foreground "forest green" :weight bold)
                   ("MEETING" :foreground "forest green" :weight bold)
                   ("PHONE" :foreground "forest green" :weight bold))))

   #+END_SRC
*** 电话
	Telephone calls are special. They are created in a done state by a capture task.
	The time of the call is recorded for as long as the capture task is active. 
	If I need to look up other details and want to close the capture task early
	I can just C-c C-c to close the capture task (stopping the clock) and then f9 SPC to resume the clock in the phone call while I do other things. 
*** 会议
	Meetings are special. 
	They are created in a done state by a capture task.
	I use the MEETING capture template when someone interrupts what I'm doing with a question or discussion. 
	This is handled similarly to phone calls where I clock the amount of time spent with whomever it is and record some notes of what was discussed (either during or after the meeting) depending on content, length, and complexity of the discussion.
*** 快速TODO状态切换
	
	开启fast todo selection,使得可以使用`C-c C-t'直接选择TODO状态
	#+BEGIN_SRC emacs-lisp
      (setq org-use-fast-todo-selection t)
	#+END_SRC

	当时用S-left和S-rigth更改TODO状态时,仅仅只是更改状态,而不要像正常的更改状态流程那样登记状态更改的时间戳,抓获切换状态时的上下文日志
	#+BEGIN_SRC emacs-lisp
      (setq org-treat-S-cursor-todo-selection-as-state-change nil)
	#+END_SRC
** TODO状态触发器

   当TODO状态发生更改时,自动添加/删除特定的TAG,这样方便agenda view中过滤任务:

    org-todo-state-tags-triggers的格式为`(state-change (tag . flag) .......)',这里state-change可以是一个表示todo状态的字符串,或者是符号'todo或'done,分别表示所有表示未完成任务的和以完成任务的todo state
   #+BEGIN_SRC emacs-lisp
     (setq org-todo-state-tags-triggers
           (quote (("CANCELLED" ("CANCELLED" . t))
                   ("WAITING" ("WAITING" . t))
                   ("HOLD" ("WAITING") ("HOLD" . t))
                   (done ("WAITING") ("HOLD"))
                   ("TODO" ("WAITING") ("CANCELLED") ("HOLD"))
                   ("NEXT" ("WAITING") ("CANCELLED") ("HOLD"))
                   ("DONE" ("WAITING") ("CANCELLED") ("HOLD")))))


     ;; * Moving a task to CANCELLED adds a CANCELLED tag
     ;; * Moving a task to WAITING adds a WAITING tag
     ;; * Moving a task to HOLD adds WAITING and HOLD tags
     ;; * Moving a task to a done state removes WAITING and HOLD tags
     ;; * Moving a task to TODO removes WAITING, CANCELLED, and HOLD tags
     ;; * Moving a task to NEXT removes WAITING, CANCELLED, and HOLD tags
     ;; * Moving a task to DONE removes WAITING, CANCELLED, and HOLD tags
   #+END_SRC
* 配置org-capture
** Capure模板  
   将task划分为一下几类:
   * A phone call(p) 
   * A meeting (m) 
   * An email I need to respond to (r) 
   * A new task (t) 
   * A new note (n) 
   * An interruption (j) 
   * A new habit (h) 
	 
   所有caputre的task都先暂存入refile.org中,再refile到各个org文件中
   #+BEGIN_SRC emacs-lisp
     (setq org-default-notes-file (concat GTD-HOME-PATH "refile.org"))
     (setq org-capture-templates
           '(("t" "TODO" entry (file+headline (concat GTD-HOME-PATH "refile.org" ) "Tasks")
              "** TODO %? \n%U\n%a\n" :clock-in t :clock-resume t) 
             ("p" "Project" entry (file+headline (concat GTD-HOME-PATH "refile.org" ) "Projects")
              "** TODO %? %^g \n" :clock-in t :clock-resume t)
             ("r" "respond" entry (file+headline (concat GTD-HOME-PATH "refile.org" ) "Tasks")
              "** NEXT Respond to %:from on %:subject\nSCHEDULED: %t\n%U\n%a\n" :clock-in t :clock-resume t :immediate-finish t)
             ("n" "Note" entry (file+headline (concat GTD-HOME-PATH "refile.org" ) "Notes")
              "* %? %x %^g" :clock-in t :clock-resume t)
             ("j" "Journal" entry (file+datetree (concat GTD-HOME-PATH "diary.org" ))
              "* %?\n%U\n" :clock-in t :clock-resume t)
             ("w" "org-protocol" entry (file (concat GTD-HOME-PATH "refile.org" ) "Tasks")
              "** TODO Review %c\n%U\n" :immediate-finish t)
             ("m" "Meeting" entry (file+headline (concat GTD-HOME-PATH "refile.org") "Tasks")
              "** MEETING with %? :MEETING:\n%U" :clock-in t :clock-resume t)
             ("p" "Phone call" entry (file+headline (concat GTD-HOME-PATH "refile.org") "Tasks")
              "** PHONE %? :PHONE:\n%U" :clock-in t :clock-resume t)
             ("h" "Habit" entry (file+headline (concat GTD-HOME-PATH "refile.org") "Habits")
              "* NEXT %?\n%U\n%a\nSCHEDULED: %(format-time-string \"<%Y-%m-%d %a .+1d/3d>\")\n:PROPERTIES:\n:STYLE: habit\n:REPEAT_TO_STATE: NEXT\n:END:\n")
             ("i" "Idea" entry (file+headline (concat GTD-HOME-PATH "refile.org" ) "Ideas")
              "** %? %x %a"  :clock-in t :clock-resume t) 
             ("b" "Books" entry (file (concat GTD-HOME-PATH "books.org" ))
              "** TODO %^{书籍名称？}  :book:"  :clock-in t :clock-resume t)))
   #+END_SRC
   
   通过设置`:clock-in t'使得在captre task时自动开始clock in. 设置`:clock-resume t'则使得capture task完成后,自动恢复原task的clock in.
   但这就会产生一个问题,若capture task的时间小于1分钟,则可能有大量的计时为0:00的记录存在,这些记录需要清理
   
   * TODO Since I remove clocking lines with 0:00 length I end up with a clock drawer like this: 
	 #+BEGIN_SRC org
       ,* TODO New Capture Task
         :LOGBOOK:  
         :END:      
         [2010-05-08 Sat 13:53]
	 #+END_SRC

   #+BEGIN_SRC emacs-lisp
     ;; Remove empty LOGBOOK drawers on clock out
     (defun bh/org-remove-empty-drawer-on-clock-out ()
       (interactive)
       (save-excursion
         (beginning-of-line 0)
         (org-remove-empty-drawer-at (point))))

     ;; (add-hook 'org-clock-out-hook 'bh/org-remove-empty-drawer-on-clock-out 'append)

   #+END_SRC
   
* 其他	
  #+BEGIN_SRC emacs-lisp
    ;; (org-remember-insinuate)
    ;; org-capture配置
    
    ;; 新增org文件时插入模版
    (defun new-org-file-init ()
      "init new org file template"
      (interactive)
      (when (equal "org" (file-name-extension buffer-file-name))
          (insert (concat "#+TITLE: "(file-name-base buffer-file-name)) "\n")
          (insert "#+AUTHOR: " user-login-name "\n")
          (insert "#+OPTIONS: ^:{}")))
    (add-to-list 'find-file-not-found-hooks 'new-org-file-init)

    ;; 设置org笔记时的缩进
    (setq org-description-max-ident 5)

    ;; 设置org template
    (add-to-list 'org-structure-template-alist '("se" "#+BEGIN_SRC emacs-lisp\n?\n#+END_SRC" "<src lang=\"emacs-lisp\">\n?\n</src>"))

    ;; 高亮显示code blocks
    (setq org-src-fontify-natively t)

    (require 'darksun-org-helper)
  #+END_SRC
